eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}

security:
  user:
    password: ${eureka.password}

spring:
  profiles: heroku
  data:
    mongodb:
      uri: ${MONGODB_URI}


#eureka.client.service-url.defaultZone=http://localhost:8761/eureka


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      
#pelo zuul http://localhost:8080/quiz-service/quizes/answers?states=SP      