eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://jcervelin-eureka.herokuapp.com/eureka
  instance:
    hostname: quiz-service.herokuapp.com

spring:
  profiles: heroku
  data:
    mongodb:
      uri: ${MONGODB_URI}


#eureka.client.service-url.defaultZone=http://localhost:8761/eureka


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      
#pelo zuul http://localhost:8080/quiz-service/quizes/answers?states=SP      